### ISSUE TITLE
想請問關於BERT QA視覺化的辦法

### ISSUE THREAD

**Issue by leo88359** [WenTingTseng/DomainClassification_FAQ#1]
曾同學您好，我有在BertViz的討論中看到您發問有關於BERT視覺化的問題 (https://github.com/jessevig/bertviz/issues/38)
看您的程式碼似乎也是基於Taipei QA Bert的架構進行運用，與我目前使用的方式雷同
但我仍不知道該如何將fine-tune好的model丟入model_version裡面，因此想請問您是否方便分享這部分的code以進行參考

感激不盡 =D

**Comment by WenTingTseng** [comment]
相關的程式碼我放在這裡，放模型相對應的路徑你再修改應該就可以使用了
https://github.com/WenTingTseng/BERTViz

**Comment by leo88359** [comment]
我會在研究修改看看，非常感謝您，也預祝您研究工作愉快順利 =D
